# Settings.yaml

Neos:
  Neos:
    fusion:
      autoInclude:
        AR.AndreasRieger: true
    nodeTypes:
      groups:
        twbs:
          position: 50
          label: 'Twitter Bootstrap Components'
          icon: 'icon-twitter-square'
