# Settings.yaml

Neos:
  Neos:
    fusion:
      autoInclude:
        AR.TwbsComponents: true
    nodeTypes:
      groups:
        twbs:
          position: 50
          label: 'Twitter Bootstrap Components'
          icon: 'icon-twitter-square'
  ContentRepository:
    contentDimensions:
      language:
        label: 'AR.AndreasRieger:Main:contentDimensions.language'
        icon: icon-language
        default: en_US
        defaultPreset: en_US
        presets:
          all: null
          en_US:
            label: 'English'
            values:
              - en_US
            uriSegment: en
          de:
            label: German
            values:
              - de
            uriSegment: de
