# Settings.yaml

Neos:
  Neos:
    fusion:
      autoInclude:
        AR.TwbsComponents: true
    nodeTypes:
      groups:
        twbs:
          position: 50
          label: 'Twitter Bootstrap Components'
          icon: 'icon-twitter-square'
  ContentRepository:
    contentDimensions:
      'language':
        label: 'Language'
        icon: 'icon-language'
        default: 'en_US'
        defaultPreset: 'en_US'
        presets:
          'all': ~
          'en_US':
            label: 'English'
            values: ['en_US']
            uriSegment: ''
          'de_DE':
            label: 'Deutsch'
            values: ['de_DE', 'en_US']
            uriSegment: 'de'
